export const myDeck = [
  {
    name: "spades-two", //spades
    value: 2
  }, {
    name: "spades-three",
    value: 3
  }, {
    name: "spades-four",
    value: 4
  }, {
    name: "spades-five",
    value: 5
  }, {
    name: "spades-six",
    value: 6
  }, {
    name: "spades-seven",
    value: 7
  }, {
    name: "spades-eight",
    value: 8
  }, {
    name: "spades-nine",
    value: 9
  }, {
    name: "spades-ten",
    value: 10
  }, {
    name: "spades-jack",
    value: 11
  }, {
    name: "spades-queen",
    value: 12
  }, {
    name: "spades-king",
    value: 13
  }, {
    name: "spades-ace",
    value: 14
  }, {       
    name: "hearts-two", // Hearts
    value: 2
  }, {
    name: "hearts-three",
    value: 3
  }, {
    name: "hearts-four",
    value: 4
  }, {
    name: "hearts-five",
    value: 5
  }, {
    name: "hearts-six",
    value: 6
  }, {
    name: "hearts-seven",
    value: 7
  }, {
    name: "hearts-eight",
    value: 8
  }, {
    name: "hearts-nine",
    value: 9
  }, {
    name: "hearts-ten",
    value: 10
  }, {
    name: "hearts-jack",
    value: 11
  }, {
    name: "hearts-queen",
    value: 12
  }, {
    name: "hearts-king",
    value: 13
  }, {
    name: "hearts-ace",
    value: 14
  }, {
    name: "diamonds-two", // Diamonds
    value: 2
  }, {
    name: "diamonds-three",
    value: 3
  }, {
    name: "diamonds-four",
    value: 4
  }, {
    name: "diamonds-five",
    value: 5
  }, {
    name: "diamonds-six",
    value: 6
  }, {
    name: "diamonds-seven",
    value: 7
  }, {
    name: "diamonds-eight",
    value: 8
  }, {
    name: "diamonds-nine",
    value: 9
  }, {
    name: "diamonds-ten",
    value: 10
  }, {
    name: "diamonds-jack",
    value: 11
  }, {
    name: "diamonds-queen",
    value: 12
  }, {
    name: "diamonds-king",
    value: 13
  }, {
    name: "diamonds-ace",
    value: 14
  }, {
    name: "clubs-two", // Clubs
    value: 2
  }, {
    name: "clubs-three",
    value: 3
  }, {
    name: "clubs-four",
    value: 4
  }, {
    name: "clubs-five",
    value: 5
  }, {
    name: "clubs-six",
    value: 6
  }, {
    name: "clubs-seven",
    value: 7
  }, {
    name: "clubs-eight",
    value: 8
  }, {
    name: "clubs-nine",
    value: 9
  }, {
    name: "clubs-ten",
    value: 10
  }, {
    name: "clubs-jack",
    value: 11
  }, {
    name: "clubs-queen",
    value: 12
  }, {
    name: "clubs-king",
    value: 13
  }, {
    name: "clubs-ace",
    value: 14
  }
]

// Array.from(myDeck);



